### PR TITLE
Add Secret QRCode, Fix #12

### LINKED ISSUE #12: print friendly version like bitcoinwallets
https://moneropaperwallet.com/

lets make it a printfriendly version, like these bitcoinwallets or the myetherwallet printouts?

### PR DESCRIPTION
**Pull request by jenniferberger**
- Add qr code that contains secrets
- Add style that makes the page suitable for printing
- minimal code cleanup (more required: incosistent variable=[blank]"value" but out of scope)

### CODE REVIEW

**Comment by m2049r** [comment]
we should have a different uri scheme for wallet definitions. the "moenro:" scheme is for payments - it should stay this way. make a new scheme "monero_wallet:" maybe.

**Comment by jenniferberger** [comment]
Good point, adapted to monero_wallet: scheme

**Comment by jenniferberger** [comment]
from the current urge to generate new paper wallets some fixes were applied:
- better printout in firefox
- corrected qr-code (at least android barcode scanner now can read it with all parameters)
- added a date to make restore more convienient

**Comment by m2049r** [comment]
nice. my phone has real trouble reading that code - can you make the modules bigger? i see no date. maybe we should add an optional ```date``` param in addition to ```height``` to the spec?

**Comment by jenniferberger** [comment]
The date is displayed on the first page in printout only (print to pdf to save paper)
making the qr-codes bigger would result in more pages - it still works with the page zoomed to 50% (130x130 @130ppi / 8mp phone cam)
good idea with the date parameter in the spec - makes it easier to create the code without a current blockchain height around. (iso_date to avoid confusions?)

**Comment by m2049r** [comment]
oh - printout is sexy. but address & keys are cut off on the right (pdf output on ubuntu from firefox).
yes, ISO 8601 is a great idea.
i am not sure it is necessary to have both spend/view keys AND seed in the qr-code. maybe seed is enough? or just the keys? since the idea is for an app to scan and use the info, maybe keys are what is right - and seed can be derived from spend key if need be. if we have both, then the scanning app will need to check if the seed matches the spend key ...

**Comment by jenniferberger** [comment]
separated the seed and keys, added iso_date
fine-tuned printout to 3 pages (public, mnemonic, keys)

**Comment by moneromooo-monero** [comment]
Apologies for letting this die out.

If you're still willing to contribute this, could you please avoid all the whitespace changes ? It makes the patch much heavier than necessary.

Has anyone else still around tried it ?

**Comment by jenniferberger** [comment]
sorry for the whitespace changes, my editor always drops them, not sure if i can re-insert them now

**Comment by moneromooo-monero** [comment]
OK, well fair enough then. Not many people changing this so it doesn't matter near as much as more active projects.

**Comment by moneromooo-monero** [comment]
Trying it now, it seems to get stuck on generation.

**Comment by moneromooo-monero** [comment]
I worked it out, fixed.

**Comment by moneromooo-monero** [comment]
Merged, thanks. Turns out all the whitespace changes were neatly in a separate commit so I just dropped it :)

**Pull request closed without merging**
