### PR TITLE
Generate wallet when user presses the enter key

### PR DESCRIPTION
**Pull request by Arux-BTT**
return false, is needed to prevent refresh page on enter key press
(another way is to not use form to prevent the form from being submitted)

### CODE REVIEW

**Comment by Hary2511** [comment]
I am can new wallet from monero

**Comment by moneromooo-monero** [comment]
Sorry, I'd totally forgot about that repo for a while :)

I see a return false; in one case and not the other. Looking for doc, I see return return false is to ignore the character. I'm not clear whether not returning anything means "random" behaviour or not though. Most of the example code I've seen returns nothing, puzzlingly, but mozilla has an example using the return value to filter input.

**Comment by Hary2511** [comment]
yes, then what should I do

Pada tanggal Rab, 10 Okt 2018 pukul 23.38 moneromooo-monero <
notifications@github.com> menulis:

**Comment by moneromooo-monero** [comment]
Thanks, that got merged.... years later ^_^

**Pull request closed without merging**
